name: Build Bridgeless Core docker image
on:
  push:
    branches:
      - 'chains/mainnet'
      - 'chains/testnet'
      - 'chains/devnet'

env:
  CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  converge-github:
    name: Build To Github
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Push Image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
          CACHE_REPO: ghcr.io/${{ github.repository }}/cache
        run: |
          buildah build \
            --format docker \
            -f Dockerfile \
            --layers \
            --cache-from $CACHE_REPO \
            --cache-to $CACHE_REPO \
            -t $IMAGE \
            --build-arg CI_ACCESS_TOKEN=$CI_ACCESS_TOKEN \
            .

      - name: Push Image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: buildah push $IMAGE
